name = "Modified Cobblemon Plus"
version = "11.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "654b41105f9717946f67c7cf70abc6c7d80acc7f57a201a06f8c9781cc845762"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.148"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
