name = "Modified Cobblemon Plus"
version = "11.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c2ef746d6913dcb0798cefd74f0d6de0462d7cc2c856135fb1784daf15385ca"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.199"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
