name = "Modified Cobblemon Plus"
version = "11.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9d13abcbd797ca439a279de9b8b858a1da6c934d4e7a92b49c072c43bdbdebe"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.205"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
