name = "Modified Cobblemon Plus"
version = "11.8.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed3d304e456085c5353e7243cb21107f394f9f0c3df9622de8ba32bdc55f1e91"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
