name = "Modified Cobblemon Plus"
version = "11.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f70d03b6b34fbc3d917dc6a1d3c54e99f67ea87d7af38cb24a8da6c94b42bbb2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
