name = "Modified Cobblemon Plus"
version = "11.9.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f39ebdff0cd3653382238538d8272c3b07f001b7d68d52900e890af52597a8bd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
