name = "Modified Cobblemon Plus"
version = "11.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2430b162e24e4fd25a52544f58267882e2a06da7af182f335ec946170a84cb5d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
