name = "Modified Cobblemon Plus"
version = "11.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f102fc85053b8b89a0d83c9d048e00da0e202ddfa42d3361dca7d8868702d636"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.148"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
