name = "Modified Cobblemon Plus"
version = "11.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d9d579bb369c537108528be510dc614e5b00263b5c1ed2bd637edae976b2f1e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.199"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
