name = "Modified Cobblemon Plus"
version = "11.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f06abf718638af88bd789673d391e9fd821e3436f584588f2b949a6d722b31d2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.199"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
