name = "Modified Cobblemon Plus"
version = "11.8.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0e028ec37abe0ab677ec727e38f4fa4cf4705684e6383c6874154868404d8fd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
