name = "Modified Cobblemon Plus"
version = "11.8.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f560c7e955e5fe9f2ae2c06b1ab091347b7995ae5189c375903c9db5e4b8e77b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.205"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
