name = "Modified Cobblemon Plus"
version = "11.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd5585cdcb27b37eda7da9e56c627b579b726f53cd493d444350680973c017ee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
