name = "Modified Cobblemon Plus"
version = "11.9.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5593835d53e66c2fb1a445ab877bf827a3e2beb87cf4b52173633bcdec797fb5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.208"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
