name = "Modified Cobblemon Plus"
version = "11.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6636585ce682b23687488fd7119a22c62924a1a5f2cda4f7d6310daa64a20089"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.199"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
