name = "Modified Cobblemon Plus"
version = "11.8.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41c526f933def70b229e320067413d60f02ca05d3b12b2b672851ed4a31cc435"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.199"

[export]
[export.curseforge]
project-id = 867058

[options]
acceptable-game-versions = ["1.21.1"]
