[Settings]
	#Enables or disables Edit Mode in the Skills Record screen.
	#Edit Mode allows customization of the Skills Record interface.
	sr_edit_mode = false

	[Settings.Visuals]
		#This config controls the list of shapes appearing on the screen.If set to ALL, it will show all shapes including blacklisted ones.If set to ENABLED_SHAPES, it will show only non-blacklisted shapes.
		#Allowed Values: ALL, ENABLED_SHAPES
		shape_selector_filter = "ALL"
		#Toggles the drop shadow effect on text in the Skills Record screen.
		#When enabled, text will have a subtle shadow for better readability.
		text_screen_shadow = true
		#Sets the background color of the Skills Record GUI.
		#Choose from predefined color options to customize the interface.
		#Allowed Values: DEFAULT, RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET
		background_color = "DEFAULT"
		#Enables or disables animations in the Skills Record GUI.
		#Animations provide visual feedback for interactions.
		animations_mode = true
		#Controls the visibility mode of the progress bar:
		#0: Always visible.
		#1: Visible only when holding its keybind.
		#2: Disabled entirely.
		# Default: 0
		# Range: 0 ~ 2
		progress_bar_mode = 0
		#Determines the position of the Challenges panel on the screen.
		#Choose from predefined positions (e.g., LEFT, RIGHT).
		#Allowed Values: DISABLED, TOP_LEFT, TOP_RIGHT, LEFT, RIGHT, BOTTOM_LEFT, BOTTOM_RIGHT
		challenges_panel_pos = "LEFT"
		#Enables or disables the Mining Skill Card Renderer.
		#Note: This feature is a work in progress (WIP) and not recommended for regular use.
		msc_renderer = false
