[Playstyle]
	#Defines the playstyle mode for the mod:
	#MODERN: Modern playstyle with new features and challenges.
	#ONE_TIER_ONLY [WIP]: Single-tier Mining Skill Card that upgrades to Mastered upon challenge completion.
	#LEGACY: Restores mechanics from v0.1.0 (only one miner certificate and one challenge).
	#NOTE: Ensure to restart the world for the changes to take effect
	#Allowed Values: MODERN, ONE_TIER_ONLY, LEGACY
	playstyle_mode = "MODERN"

[Trades]
	#Defines the required trade level for card trading with villagers.
	#NOTE: Ensure to restart the world for the changes to take effect
	# Default: 1
	# Range: 1 ~ 5
	card_trade_level = 1
	#Defines the trade price range for Mining Skill Cards.
	#Range: 1 ~ 256.
	card_trade_price = "8, 20"
